#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

if [[ -z "$STAGED_GO_FILES" ]]; then
  echo "No staged Go files changed. Skipping pre-commit checks."
  exit 0
fi

printf "Running pre-commit checks on staged Go files...\n"

# Run golangci-lint on all staged files. Capture and display output.
golangci-lint run --config=.golangci.yaml $(echo "$STAGED_GO_FILES")
if [[ $? != 0 ]]; then
  printf "golangci-lint checks failed. Please fix the issues and stage the changes.\n"
  exit 1
fi

# Format all staged files in one command.
go fmt $(echo "$STAGED_GO_FILES")

# Organize imports for all staged files in one command.
goimports -w $(echo "$STAGED_GO_FILES")

printf "Pre-commit checks passed.\n"
exit 0