linters-settings:
  goimports:
    local-prefixes: gitlab.com/ersvitation/user # Replace with your module name

  gocyclo:
    min-complexity: 20

  errcheck:
    exclude-functions:
      - Close # Updated from `exclude` to `exclude-functions`

  funlen:
    lines: 60
    statements: 20

run:
  timeout: 2m

linters:
  disable-all: true # Start with all linters disabled, then enable only the ones you want
  enable:
    - whitespace
    - stylecheck
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - govet
    - gocritic
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  exclude-dirs: # Updated from `run.skip-dirs`
    - vendor
  exclude-files: # Updated from `run.skip-files`
    - ".*_test.go"

output:
  formats: # Use a map format for output
    - format: colored-line-number
  sort-results: true