run:
  timeout: 5m
  concurrency: 10

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - goimports
    - staticcheck
    - gocritic
    - unconvert
    - misspell
    # Add other linters as needed

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-rules:
  # Add exclusions as needed